# Turn compiled SPIR-V into a C++ source file. Script mode; see
# add_spirv_shaders(... EMBED) in CompileShaders.cmake for the caller.
# SPDX-License-Identifier: GPL-3.0-or-later
#
#     cmake -DOUTPUT=<file.cpp> -DNAMES=a;b -DFILES=a.spv;b.spv
#           -DCOMPILER=<glslc|glslang> -P EmbedSpirv.cmake
#
# The words are emitted as integer constants rather than as bytes, so the array
# is correct whatever the endianness of the machine that later compiles it. The
# .spv files themselves are little endian, which is checked here: a big-endian
# module would be silently wrong, and no toolchain this project supports
# produces one.
#
# What this cannot do is make the result reproducible. glslc and
# glslangValidator emit different modules from the same source -- different
# lengths, not just different bytes -- and each is only as proven as the
# toolchain that produced it. The generated file records which one built it so
# that a bug report says so too.

if(NOT OUTPUT OR NOT NAMES OR NOT FILES)
    message(FATAL_ERROR "EmbedSpirv: OUTPUT, NAMES and FILES are all required")
endif()

set(body "// Generated by EmbedSpirv.cmake. Do not edit.\n")
string(APPEND body "// SPDX-License-Identifier: GPL-3.0-or-later\n")
string(APPEND body "//\n")
string(APPEND body "// Built with: ${COMPILER}. Modules from a different GLSL\n")
string(APPEND body "// compiler are not the same bytes and are not interchangeable\n")
string(APPEND body "// as evidence that a shader works.\n\n")
string(APPEND body "#include \"shaders/embedded.h\"\n\n")
string(APPEND body "namespace vkminer {\nnamespace {\n\n")

set(table "")
list(LENGTH NAMES count)
math(EXPR last_index "${count} - 1")

foreach(i RANGE ${last_index})
    list(GET NAMES ${i} name)
    list(GET FILES ${i} file)

    if(NOT EXISTS "${file}")
        message(FATAL_ERROR "EmbedSpirv: ${file} does not exist")
    endif()

    file(READ "${file}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR remainder "${hex_len} % 8")
    if(NOT remainder EQUAL 0)
        message(FATAL_ERROR
            "EmbedSpirv: ${file} is not a whole number of 32-bit words")
    endif()
    math(EXPR word_count "${hex_len} / 8")

    # SPIR-V's magic number, little endian on disk: 0x07230203 -> 03 02 23 07.
    string(SUBSTRING "${hex}" 0 8 magic)
    if(NOT magic STREQUAL "03022307")
        message(FATAL_ERROR
            "EmbedSpirv: ${file} does not start with a little-endian SPIR-V "
            "magic number (found ${magic})")
    endif()

    string(MAKE_C_IDENTIFIER "${name}" ident)
    string(APPEND body "const uint32_t k_${ident}[] = {\n")

    math(EXPR last_word "${word_count} - 1")
    set(line "   ")
    foreach(w RANGE ${last_word})
        math(EXPR offset "${w} * 8")
        string(SUBSTRING "${hex}" ${offset} 8 word_hex)
        string(SUBSTRING "${word_hex}" 0 2 b0)
        string(SUBSTRING "${word_hex}" 2 2 b1)
        string(SUBSTRING "${word_hex}" 4 2 b2)
        string(SUBSTRING "${word_hex}" 6 2 b3)
        string(APPEND line " 0x${b3}${b2}${b1}${b0}u,")

        math(EXPR column "(${w} + 1) % 6")
        if(column EQUAL 0)
            string(APPEND body "${line}\n")
            set(line "   ")
        endif()
    endforeach()
    if(NOT line STREQUAL "   ")
        string(APPEND body "${line}\n")
    endif()

    string(APPEND body "};\n\n")
    string(APPEND table "    { \"${name}\", k_${ident}, ${word_count} },\n")
endforeach()

string(APPEND body "const SpirvBlob kBlobs[] = {\n${table}};\n\n")
string(APPEND body "}  // namespace\n\n")
string(APPEND body
"const SpirvBlob *find_embedded_spirv(const char *name)
{
    if (!name)
        return nullptr;
    for (const SpirvBlob &blob : kBlobs)
        if (std::strcmp(blob.name, name) == 0)
            return &blob;
    return nullptr;
}

const char *embedded_spirv_compiler() { return \"${COMPILER}\"; }

}  // namespace vkminer
")

# Written through a temporary so that a failed run cannot leave a half-written
# source file that the next build happily compiles.
file(WRITE "${OUTPUT}.tmp" "${body}")
file(RENAME "${OUTPUT}.tmp" "${OUTPUT}")
